CREATE DATABASE AgenciaViagensDB;

USE AgenciaViagensDB;

CREATE TABLE ClienteFisico (
	IDClienteFisico INT PRIMARY KEY auto_increment NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	RG VARCHAR(9) NOT NULL,
	NOME VARCHAR(45) NOT NULL,
	EMAIL VARCHAR(45) NOT NULL,
	RUA VARCHAR(45) NOT NULL,
	NUMERO VARCHAR(5) NOT NULL,
	CIDADE VARCHAR(45) NOT NULL,
	ESTADO VARCHAR(2) NOT NULL,
	COMPLEMENTO VARCHAR(45),
	CEP VARCHAR(8),
	TELEFONE VARCHAR(11) NOT NULL
);

CREATE TABLE ClienteJuridico (
	IDClienteJuridico INT PRIMARY KEY auto_increment NOT NULL,
	CNPJ VARCHAR(14) NOT NULL,
	NOME VARCHAR(45) NOT NULL,
	RUA VARCHAR(45) NOT NULL,
	NUMERO VARCHAR(5) NOT NULL,
	CIDADE VARCHAR(45) NOT NULL,
	ESTADO VARCHAR(2) NOT NULL,
	COMPLEMENTO VARCHAR(45),
	CEP VARCHAR(8) NOT NULL,
	TELEFONE VARCHAR(11) NOT NULL
);

CREATE TABLE Viagem (
	IDViagem INT PRIMARY KEY auto_increment NOT NULL,
	IDClienteJuridico INT NOT NULL,
	PARTIDA VARCHAR(45) NOT NULL,
	DESTINO VARCHAR(45) NOT NULL,
	VALOR DECIMAL(6, 2) NOT NULL,
	DATA DATETIME NOT NULL
);

CREATE TABLE Pedido (
	IDPedido INT PRIMARY KEY auto_increment NOT NULL,
	IDClienteFisico INT NOT NULL,
	IDViagem INT NOT NULL,
	CPFpassageiro VARCHAR(11) NOT NULL,
	NOMEpassageiro VARCHAR(45) NOT NULL,
	RGpassageiro VARCHAR(9) NOT NULL,
	QUANTIDADE INT
);


ALTER TABLE Pedido ADD FOREIGN KEY(IDClienteFisico) REFERENCES ClienteFisico (IDClienteFisico);
ALTER TABLE Pedido ADD FOREIGN KEY(IDViagem) REFERENCES Viagem (IDViagem);
ALTER TABLE Viagem ADD FOREIGN KEY(IDClienteJuridico) REFERENCES ClienteJuridico (IDClienteJuridico);
